apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-creator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: room-server
  namespace: default
roleRef:
  kind: Role
  name: service-creator
  apiGroup: rbac.authorization.k8s.io