apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/backend
images:
- name: re5nardo/lobby-server
  newName: re5nardo/lobby-server
  newTag: e4d7b58
- name: re5nardo/lop-db-migrate
  newName: re5nardo/lop-db-migrate
  newTag: e4d7b58
- name: re5nardo/matchmaking-server
  newName: re5nardo/matchmaking-server
  newTag: e4d7b58
- name: re5nardo/room-server
  newName: re5nardo/room-server
  newTag: e4d7b58
configMapGenerator:
- envs:
  - game-server-config.env
  name: game-server-config
