apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/backend
images:
- name: re5nardo/lobby-server
  newName: re5nardo/lobby-server
  newTag: 9937c81
- name: re5nardo/matchmaking-server
  newName: re5nardo/matchmaking-server
  newTag: 9937c81
- name: re5nardo/room-server
  newName: re5nardo/room-server
  newTag: 9937c81
- name: re5nardo/lop-db-migrate
  newName: re5nardo/lop-db-migrate
  newTag: 9937c81
configMapGenerator:
- name: game-server-config
  envs:
  - game-server-config.env
