apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-creator-role.yaml
  - namespace-reader-role.yaml
  - pod-creator-role.yaml
  - pod-deleter-role.yaml
  - pod-reader-role.yaml
  - service-creator-role.yaml
  - service-deleter-role.yaml
  - service-reader-role.yaml
  - rolebinding-namespace-creator.yaml
  - rolebinding-namespace-reader.yaml
  - rolebinding-pod-creator.yaml
  - rolebinding-pod-deleter.yaml
  - rolebinding-pod-reader.yaml
  - rolebinding-service-creator.yaml
  - rolebinding-service-deleter.yaml
  - rolebinding-service-reader.yaml
