apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- room-server-configmap.yaml
- room-server-deployment.yaml
- room-server-service.yaml
- serviceaccount.yaml
images:
- name: re5nardo/room-server
  newName: re5nardo/room-server
  newTag: e08245e
